BLACK = "#000000"
WHITE = "#FFFFFF"
HEIGHT, WIDTH = 800, 1200
MINIMUM_HEIGHT = HEIGHT - 200
MINIMUM_WIDTH = WIDTH - 200
FONT = ("bold", 24)
ANIMATION_FRAMES = ["/", "--", "\\"] # PLACEHOLDER UNTIL/IF WE IMPLEMENT A LOADING BAR

