BLACK = "#000000"
WHITE = "#FFFFFF"
HEIGHT, WIDTH = 600, 1000
MINIMUM_HEIGHT = HEIGHT - 200
MINIMUM_WIDTH = WIDTH
FONT = ("bold", 24)
ANIMATION_FRAMES = ["/", "---", "\\"] # PLACEHOLDER UNTIL/IF WE IMPLEMENT A LOADING BAR

